### ISSUE TITLE
Question on texture-less rope.

### ISSUE THREAD

**Issue by changhaonan** [RMDLO/trackdlo#62]
Hi, 

I'd like to know if this algorithm support textureless, e.g. Cable. It seems that the bag provided is mostly a textured rope.

**Comment by jingyi-xiang** [comment]
Yes, the textured rope bag files provided are only for quantitative evaluation. I will update the readme soon to include more details.

**Comment by hollydinkel** [comment]
Hi @changhaonan - thank you for your question! We do not use any texture information in the TrackDLO algorithm. TrackDLO requires a segmentation of the DLO for each frame, but this is obtained through HSV thresholding. You can find the HSV thresholding values we use for our objects in the [`trackdlo.launch`](https://github.com/RMDLO/trackdlo/blob/master/launch/trackdlo.launch) file. You can also see other types of objects we trackded in our [demonstration video](https://www.youtube.com/watch?v=MxqNJsen5eg). I hope this helps - please let us know if you have any more questions!
