### ISSUE TITLE
Question about environment

### ISSUE THREAD

**Issue by gcxjose** [RMDLO/trackdlo#72]
I thought if the scipy 1.23.3 and numpy 1.9.1 versions are reversed. Cause 1.23 is obviously a version of numpy, and scipy has just been updated to 1.10. By the way, could you please double check your environment configuration? Including the python version, thanks a lot.

**Comment by jingyi-xiang** [comment]
Sorry for the late reply, but thanks for pointing that out! The NumPy and SciPy versions in readme should be correct now. I have tested our code on three different computers, and the two I currently have access to both have Python 3.8.10. Let me know if there is anything else you would like me to check.

Additionally, if you are trying to use the docker files, I don't think they are working currently. I was not in charge of the docker file development but I was told that there are some issues.

**Comment by hollydinkel** [comment]
Hi @gcxjose - thank you for asking for clarification on which environment configurations we have tested with TrackDLO. The provided [Dockerfile.noetic](https://github.com/RMDLO/trackdlo/blob/master/docker/Dockerfile.noetic) should now build properly (it passes the Github CI build check). The docker image it builds includes a complete environment for testing TrackDLO. I verified this through playback of our experiment `.bag` files and running TrackDLO on these files inside the container. The link to our `.bag` files is in the [`RUN.md`](https://github.com/RMDLO/trackdlo/blob/master/docs/RUN.md) file. Please let me know if you encounter any further dependency issues - I can help debug! 

Closing this issue - a complete [python environment](https://github.com/RMDLO/trackdlo/blob/master/docker/requirements.txt) is provided in the docker environment.
