### ISSUE TITLE
Failed to extract splines during Initializing...

### ISSUE THREAD

**Issue by CAN-Lee** [RMDLO/trackdlo#80]
Hi, thank you for your great work that inspires me a lot. I carefully followed you instructions to run TrackDLO with recorded ROS Bag Data. But I encounter a problem during Initializing, i.e.,  Failed to extract splines, on the all ROS Bag data. Please see the figures below. Thanks for your help.
![微信截图_20240229222645](https://github.com/RMDLO/trackdlo/assets/40562225/01494238-4b2c-4489-a2b3-9689a9ebcd10)
![微信截图_20240229222554](https://github.com/RMDLO/trackdlo/assets/40562225/f8312182-ec43-4ed8-ab11-1a75e5700172)

**Comment by CAN-Lee** [comment]
Since I test on your ROS bag data, I think it is not necessary to modify the given camera topics.

**Comment by hollydinkel** [comment]
Hi @CAN-Lee ,

Thanks for raising this issue. Are you using our docker container? As a previous issue noted (https://github.com/RMDLO/trackdlo/issues/79#issuecomment-1967036328), the `skeletonization` function is sensitive to `skimage` versioning. You might check that first to see if that might be causing problems. From what I recall, the code we have in this repository works with the provided .Dockerfile and rosbag data.

**Comment by CAN-Lee** [comment]
Hi @hollydinkel ,
I really appreciate it. According to your suggestion, it works on one of ROS Bag data. I am not using docker container. Thank you.
![微信截图_20240301165340](https://github.com/RMDLO/trackdlo/assets/40562225/8f235f3f-a42b-4095-ac53-be1e5e8c1b22)
